# language options
lang: de-DE
csquotes: true

# layout options
documentclass: report
classoption:
  - a4paper
  - ngerman
  - 12pt
  - twoside
geometry:
  - margin=2.5cm
pagestyle: headings
numbersections: true

# table of contents, list of tables, figures, listings
toc: true
lot: true
lof: true
lol: true

# bibliography options
biblatex: true
csl: ./resources/elsevier-harvard.csl
bibliography: biblio.bib
reference-section-title: Literaturverzeichnis

# title page information
title: My Big Fat Studienarbeit
author: Studenty McStudentface
type: Studienarbeit
studentid: 69420

deadline: Never
duration: Forever

schoolname: School of Accounting Magic
schoollogo: imgs/lipsum_logo_2
schooladvisor: Ädvisör Ädvisörsson

degreetype: Bachelor
subject: Creative Bookkeeping
courseid: WTF420BBQ

# company info
# set "company: false" to remove this information from title page
company: true
companyname: Enron Corporation
companylocation: Omaha, Nebraska, USA
companylogo: imgs/lipsum_logo_1
companyadvisor: Advisory McAdvisorface

# statement of originality and NDA, set "true" to show, false otherwise
statement: true
nda: false
